#!/bin/bash 
#!
#SBATCH --ntasks NPROCS 
#SBATCH --job-name ORCA2_SETTE_TEST 
#SBATCH --output log_%jo 
#SBATCH --error  log_%j.e
#SBATCH --time 30:00
#SBATCH --qos=debug

#
# Test specific settings. Do not hand edit these lines; the fcm_job.sh script will set these
# (via sed operating on this template job file). 
#
  OCEANCORES=NPROCS
  export SETTE_DIR=DEF_SETTE_DIR

###############################################################
#
# set up mpp computing environment
#
# Local settings for machine IBM Power6 (VARGAS at IDRIS France)
#
export MPIRUN="mpiexec -n $OCEANCORES"
module purge
module load intel/2018.3
module load impi/2018.3
module load netcdf/4.2
module load hdf5/1.8.19
module load perl
module list

#
# load sette functions (only post_test_tidyup needed)
#
  . ${SETTE_DIR}/all_functions.sh

# Don't remove neither change the following comment line
# BODY


#
# These variables are needed by post_test_tidyup function in all_functions.sh
#
  export EXE_DIR=DEF_EXE_DIR
  export INPUT_DIR=DEF_INPUT_DIR
  export CONFIG_DIR=DEF_CONFIG_DIR
  export TOOLS_DIR=DEF_TOOLS_DIR
  export NEMO_VALIDATION_DIR=DEF_NEMO_VALIDATION
  export NEW_CONF=DEF_NEW_CONF
  export CMP_NAM=DEF_CMP_NAM
  export TEST_NAME=DEF_TEST_NAME
#
# end of set up


###############################################################
#
# change to the working directory 
#
cd ${EXE_DIR}

sed '/def_nemo-ice/d' ${INPUT_DIR}/context_nemo.xml | sed '/def_nemo-pisces/d' > context_nemo.xml
  echo Running on host `hostname`
  echo Time is `date`
  echo Directory is `pwd`
# 
#  Run the parallel MPI executable 
#
  if [ MPI_FLAG == "yes" ]; then
  echo "Running time ${MPIRUN} ./nemo"
     time ${MPIRUN} ./nemo
  else
  echo "Running time./nemo"
     time ./nemo
  fi


#
  post_test_tidyup

# END_BODY
# Don't remove neither change the previous comment line

  exit
